### ISSUE TITLE
how  to  use as  console  application

### ISSUE THREAD

**Issue by vikashsingh009** [eaba/SharpPulsar#1]
hi,
I  want  to  use  sharpPulsar  client  in  c#  console  application  ,any  public  nuget  dll  available  or  doc  so  that  i  will  follow  and  test  besic  consumer  and   producer for  pulsar  .i  see  intersting  here  support  schema which  i  am  quite  intresting  in  tests

**Comment by eaba** [comment]
Hi @vikashsingh009 
Am still working on SharpPulsar and my aim right now is to get it to build without errors - am porting from the java client.
I hope to make it ready as soon as possible!
I appreciate that you want to use SharpPulsar!
