### ISSUE TITLE
How to use admin client to get stats (interface / docs unclear)

### ISSUE THREAD

**Issue by zblocker280** [eaba/SharpPulsar#155]
I'd like to use the admin client to query topic stats and grab the value `subscriptions[$subscriptionName].consumers[$consumerName].keyHashRanges`.  However, based on the interface `IPulsarAdminRESTAPIClient`, it appears that the `GetStatsAsync` call merely returns a `Task` - it is not clear how to consume the JSON results of this API call and extract the value I want.  I don't see anything about it in the tutorials or README files either.  Could you provide a very quick usage sample, please?

**Comment by eaba** [comment]
Sorry about the delay, I will investigate. @zblocker280

**Comment by eaba** [comment]
[Fix] GetStats
- `GetStats2Async` persistent
-  `GetStatsAsync` non-persistent

**Comment by zblocker280** [comment]
Thank you!
