### ISSUE TITLE
Can SchemaGenerator be extracted?

### ISSUE THREAD

**Issue by Lanayx** [eaba/SharpPulsar#4]
Hi! I'm implementing schema for Pulsar.Client and came to the same solution as you - it's convenient to have schema generated on the fly. What do you think about extracting [this file](https://github.com/eaba/SharpPulsar/blob/master/SharpPulsar/Impl/Schema/GenerateSchema.cs) to separate repo/nuget? It can be improved as well, for example adding cache.

**Comment by eaba** [comment]
Sorry just seeing this.
It is a good idea and I will work on it.
I will let you know when it is done.

**Comment by eaba** [comment]
Done here https://github.com/eaba/SharpPulsar.SchemaGenerator and here https://www.nuget.org/packages/SharpPulsar.SchemaGenerator

**Comment by Lanayx** [comment]
Thank you! I would call it AvroSchemaGenerator, since there is no dependency on Pulsar

**Comment by eaba** [comment]
Okies.....PR is welcomed

**Comment by Lanayx** [comment]
Sure, I'm be adding PRs, but since you agreed to lead that project, I expect you to do some ground work to make it production-ready, e.g adding bunch of unit tests that prove it's work, adding some description to that repo, adding license information

**Comment by eaba** [comment]
I will do my best!
